#!/usr/bin/env bash
# creates a file containing its pid
# displays "To infinity and beyond" definitely
# displays "Y U no love me?!" when receiving SIGINT
# displays "I hate the kill command" when receiving SIGTERM
# deletes the file and terminate itself when receiving SIGQUIT

echo "$$" > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
